### ISSUE TITLE
Consider hashing  STRING columns as UTF-8 instead of UTF-16 in HLL

### ISSUE THREAD

**Issue by csringhofer** [apache/datasketches-hive#54]
Currently the HLL implementation hashes STRING columns by converting the value the java.lang.string, and then hash the underlying UTF-16 char array: 
https://github.com/apache/incubator-datasketches-hive/blob/master/src/main/java/org/apache/datasketches/hive/hll/SketchState.java#L66

This is looks like an optimization at first, as the UTF-16->UTF-8 conversion can be skipped, but actually Hive stores STRINGs as hadoop.io.text as far as I know, which holds the string as UTF-8 encoded byte arrays:
https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/Text.java#L214

This came up during Apache's Impala's HLL implementation, which should be compatible with Apache Hive's existing DataSketches wrapper. As Impala stores strings as byte arrays, converting the values to UTF-16 adds overhead and can also cause problems for byte arrays that cannot be converted to UTF-16.

**Comment by leerho** [comment]
Changing this will be fraught with problems as other Hive users may have a history of sketches created with Strings encoded as char[].  I'm not sure I see an easy solution other than documenting it & putting warnings everywhere.  Any ideas?

**Comment by AlexanderSaydakov** [comment]
Yes, I would think that we should provide a new way leaving the current way alone and  explain tradeoffs in the documentation.

**Comment by leerho** [comment]
I have created a [DISCUSS] thread on our dev@datasketches.apache.org list if you wish to add comments to that.

**Comment by leerho** [comment]
Perhaps, this is moot.  Both Pig/HLL and Hive/HLL allow updating the sketch as a raw byte[].  So the user could do their own encoding and present the sketches with byte[].  

I checked Theta and Tuple for both Pig and Hive and the same options exist.

**Comment by leerho** [comment]
This should be documented where users can find it. :)

**Comment by leerho** [comment]
This issue can now be closed.
